# PART is artix7 xc7a200tfbg676

#
####
#######
##########
#############
#################
## System level constraints
#
set_property MARK_DEBUG true [get_nets {U3/cmd_id_DUT_num[0]}]
set_property MARK_DEBUG true [get_nets {U3/cmd_id_DUT_num[1]}]
set_property MARK_DEBUG true [get_nets {U3/cmd_id_DUT_num[2]}]
set_property MARK_DEBUG true [get_nets {U3/count_addr_Q[3]}]
set_property MARK_DEBUG true [get_nets {U3/count_addr_Q[2]}]
set_property MARK_DEBUG true [get_nets {U3/count_addr_Q[0]}]
set_property MARK_DEBUG true [get_nets {U3/count_addr_Q[1]}]
set_property MARK_DEBUG true [get_nets {U3/count_addr_Q[4]}]
set_property MARK_DEBUG true [get_nets {U3/count_addr_Q[5]}]
set_property MARK_DEBUG true [get_nets {U3/count_addr_Q[6]}]
set_property MARK_DEBUG true [get_nets {U3/DIN_ESB_s[0]}]
set_property MARK_DEBUG true [get_nets {U3/DIN_ESB_s[1]}]
set_property MARK_DEBUG true [get_nets {U3/DIN_ESB_s[2]}]
set_property MARK_DEBUG true [get_nets {U3/DIN_ESB_s[3]}]
set_property MARK_DEBUG true [get_nets {U3/DIN_ESB_s[4]}]
set_property MARK_DEBUG true [get_nets {U3/DIN_ESB_s[5]}]
set_property MARK_DEBUG true [get_nets {U3/DIN_ESB_s[7]}]
set_property MARK_DEBUG true [get_nets {U3/DIN_ESB_s[6]}]
set_property MARK_DEBUG true [get_nets {U3/monitor_enable[0]}]
set_property MARK_DEBUG true [get_nets {U3/monitor_enable[1]}]
set_property MARK_DEBUG true [get_nets {U3/monitor_enable[2]}]
set_property MARK_DEBUG true [get_nets {U3/monitor_enable[3]}]
set_property MARK_DEBUG true [get_nets {U3/PCPU100u_DUT[0]}]
set_property MARK_DEBUG true [get_nets {U3/PCPU100u_DUT[1]}]
set_property MARK_DEBUG true [get_nets {U3/PCPU100u_DUT[2]}]
set_property MARK_DEBUG true [get_nets {U3/PCPU100u_DUT[3]}]
set_property MARK_DEBUG true [get_nets {U3/PCPU100u_dutq[0]}]
set_property MARK_DEBUG true [get_nets {U3/PCPU100u_dutq[1]}]
set_property MARK_DEBUG true [get_nets {U3/PCPU100u_dutq[2]}]
set_property MARK_DEBUG true [get_nets {U3/PCPU100u_dutq[3]}]
set_property MARK_DEBUG true [get_nets {U3/valid_uart[2]}]
set_property MARK_DEBUG true [get_nets {U3/valid_uart[0]}]
set_property MARK_DEBUG true [get_nets {U3/valid_uart[1]}]
set_property MARK_DEBUG true [get_nets {U3/valid_uart[3]}]
set_property MARK_DEBUG true [get_nets U3/reset_dut1]
set_property MARK_DEBUG true [get_nets {U4/U1_UMC/uart_rx_ctl_i0/rx_data[0]}]
set_property MARK_DEBUG true [get_nets {U4/U1_UMC/uart_rx_ctl_i0/rx_data[1]}]
set_property MARK_DEBUG true [get_nets {U4/U1_UMC/uart_rx_ctl_i0/rx_data[5]}]
set_property MARK_DEBUG true [get_nets {U4/U1_UMC/uart_rx_ctl_i0/rx_data[3]}]
set_property MARK_DEBUG true [get_nets {U4/U1_UMC/uart_rx_ctl_i0/rx_data[2]}]
set_property MARK_DEBUG true [get_nets {U4/U1_UMC/uart_rx_ctl_i0/rx_data[4]}]
set_property MARK_DEBUG true [get_nets {U4/U1_UMC/uart_rx_ctl_i0/rx_data[6]}]
set_property MARK_DEBUG true [get_nets {U4/U1_UMC/uart_rx_ctl_i0/rx_data[7]}]
set_property MARK_DEBUG true [get_nets U4/U1_UMC/uart_rx_ctl_i0/rx_data_rdy]
set_property MARK_DEBUG true [get_nets U4/U1_UMC/uart_rx_ctl_i0/valid_dut]
create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 4 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER true [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL true [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list clock]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 8 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {U4/U1_UMC/uart_rx_ctl_i0/rx_data[0]} {U4/U1_UMC/uart_rx_ctl_i0/rx_data[1]} {U4/U1_UMC/uart_rx_ctl_i0/rx_data[2]} {U4/U1_UMC/uart_rx_ctl_i0/rx_data[3]} {U4/U1_UMC/uart_rx_ctl_i0/rx_data[4]} {U4/U1_UMC/uart_rx_ctl_i0/rx_data[5]} {U4/U1_UMC/uart_rx_ctl_i0/rx_data[6]} {U4/U1_UMC/uart_rx_ctl_i0/rx_data[7]}]]
create_debug_core u_ila_1 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_1]
set_property ALL_PROBE_SAME_MU_CNT 4 [get_debug_cores u_ila_1]
set_property C_ADV_TRIGGER true [get_debug_cores u_ila_1]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_1]
set_property C_EN_STRG_QUAL true [get_debug_cores u_ila_1]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_1]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_1]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_1]
set_property port_width 1 [get_debug_ports u_ila_1/clk]
connect_debug_port u_ila_1/clk [get_nets [list mac1/example_clocks/clock_generator/CLK_OUT2]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe0]
set_property port_width 4 [get_debug_ports u_ila_1/probe0]
connect_debug_port u_ila_1/probe0 [get_nets [list {U3/PCPU100u_DUT[0]} {U3/PCPU100u_DUT[1]} {U3/PCPU100u_DUT[2]} {U3/PCPU100u_DUT[3]}]]
create_debug_core u_ila_2 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_2]
set_property ALL_PROBE_SAME_MU_CNT 4 [get_debug_cores u_ila_2]
set_property C_ADV_TRIGGER true [get_debug_cores u_ila_2]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_2]
set_property C_EN_STRG_QUAL true [get_debug_cores u_ila_2]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_2]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_2]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_2]
set_property port_width 1 [get_debug_ports u_ila_2/clk]
connect_debug_port u_ila_2/clk [get_nets [list mac1/example_clocks/clock_generator/CLK_OUT3]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_2/probe0]
set_property port_width 1 [get_debug_ports u_ila_2/probe0]
connect_debug_port u_ila_2/probe0 [get_nets [list U4/U1_UMC/uart_rx_ctl_i0/valid_dut]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 8 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {U3/DIN_ESB_s[0]} {U3/DIN_ESB_s[1]} {U3/DIN_ESB_s[2]} {U3/DIN_ESB_s[3]} {U3/DIN_ESB_s[4]} {U3/DIN_ESB_s[5]} {U3/DIN_ESB_s[6]} {U3/DIN_ESB_s[7]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 4 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list {U3/monitor_enable[0]} {U3/monitor_enable[1]} {U3/monitor_enable[2]} {U3/monitor_enable[3]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property port_width 4 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list {U3/valid_uart[0]} {U3/valid_uart[1]} {U3/valid_uart[2]} {U3/valid_uart[3]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property port_width 3 [get_debug_ports u_ila_0/probe4]
connect_debug_port u_ila_0/probe4 [get_nets [list {U3/cmd_id_DUT_num[0]} {U3/cmd_id_DUT_num[1]} {U3/cmd_id_DUT_num[2]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property port_width 7 [get_debug_ports u_ila_0/probe5]
connect_debug_port u_ila_0/probe5 [get_nets [list {U3/count_addr_Q[0]} {U3/count_addr_Q[1]} {U3/count_addr_Q[2]} {U3/count_addr_Q[3]} {U3/count_addr_Q[4]} {U3/count_addr_Q[5]} {U3/count_addr_Q[6]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe6]
set_property port_width 1 [get_debug_ports u_ila_0/probe6]
connect_debug_port u_ila_0/probe6 [get_nets [list U4/U1_UMC/uart_rx_ctl_i0/rx_data_rdy]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe1]
set_property port_width 4 [get_debug_ports u_ila_1/probe1]
connect_debug_port u_ila_1/probe1 [get_nets [list {U3/PCPU100u_dutq[0]} {U3/PCPU100u_dutq[1]} {U3/PCPU100u_dutq[2]} {U3/PCPU100u_dutq[3]}]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe2]
set_property port_width 1 [get_debug_ports u_ila_1/probe2]
connect_debug_port u_ila_1/probe2 [get_nets [list U3/reset_dut1]]

set_property IOSTANDARD LVCMOS33 [get_ports glbl_rst]
set_property IOSTANDARD LVCMOS33 [get_ports {Monitor_enable[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Monitor_enable[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Monitor_enable[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {Monitor_enable[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {PCPU100u_DUT[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {PCPU100u_DUT[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {PCPU100u_DUT[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {PCPU100u_DUT[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {PCPU100u_DUTq[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {PCPU100u_DUTq[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {PCPU100u_DUTq[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {PCPU100u_DUTq[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {PCPU_status[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {PCPU_status[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RX_UT_p[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RX_UT_p[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RX_UT_p[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RX_UT_p[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {PCPU_status[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {PCPU_status[2]}]

set_property IOSTANDARD LVDS_25 [get_ports sma_clk_p]
set_property IOSTANDARD LVDS_25 [get_ports sma_clk_n]
set_property IOSTANDARD LVDS_25 [get_ports clk_in_p]
set_property IOSTANDARD LVDS_25 [get_ports clk_in_n]
set_property IOSTANDARD LVCMOS18 [get_ports mdc]
set_property IOSTANDARD LVCMOS18 [get_ports mdio]
set_property PACKAGE_PIN V18 [get_ports phy_resetn]
set_property IOSTANDARD HSTL_I_18 [get_ports phy_resetn]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets clk_200]
