# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: I:/ac701_SAC/mac_ip_example.srcs/sources_1/ip/fifo_wbb/fifo_wbb.xci
# IP: The module: 'fifo_wbb' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: i:/ac701_SAC/mac_ip_example.srcs/sources_1/ip/fifo_wbb/fifo_wbb/fifo_wbb_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_wbb'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: i:/ac701_SAC/mac_ip_example.srcs/sources_1/ip/fifo_wbb/fifo_wbb/fifo_wbb.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_wbb'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: i:/ac701_SAC/mac_ip_example.srcs/sources_1/ip/fifo_wbb/fifo_wbb_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_wbb'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# IP: I:/ac701_SAC/mac_ip_example.srcs/sources_1/ip/fifo_wbb/fifo_wbb.xci
# IP: The module: 'fifo_wbb' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: i:/ac701_SAC/mac_ip_example.srcs/sources_1/ip/fifo_wbb/fifo_wbb/fifo_wbb_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_wbb'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: i:/ac701_SAC/mac_ip_example.srcs/sources_1/ip/fifo_wbb/fifo_wbb/fifo_wbb.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_wbb'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: i:/ac701_SAC/mac_ip_example.srcs/sources_1/ip/fifo_wbb/fifo_wbb_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_wbb'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
