# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: i:/rgmii/viv16/mac_ip_example/mac_ip_example.srcs/sources_1/ip/fifo_data/fifo_data.xci
# IP: The module: 'fifo_data' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: i:/rgmii/viv16/mac_ip_example/mac_ip_example.srcs/sources_1/ip/fifo_data/fifo_data/fifo_data_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_data'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: i:/rgmii/viv16/mac_ip_example/mac_ip_example.srcs/sources_1/ip/fifo_data/fifo_data/fifo_data.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_data'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: i:/rgmii/viv16/mac_ip_example/mac_ip_example.srcs/sources_1/ip/fifo_data/fifo_data_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_data'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# IP: i:/rgmii/viv16/mac_ip_example/mac_ip_example.srcs/sources_1/ip/fifo_data/fifo_data.xci
# IP: The module: 'fifo_data' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: i:/rgmii/viv16/mac_ip_example/mac_ip_example.srcs/sources_1/ip/fifo_data/fifo_data/fifo_data_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_data'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: i:/rgmii/viv16/mac_ip_example/mac_ip_example.srcs/sources_1/ip/fifo_data/fifo_data/fifo_data.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_data'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: i:/rgmii/viv16/mac_ip_example/mac_ip_example.srcs/sources_1/ip/fifo_data/fifo_data_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_data'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
