# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: i:/rgmii/viv16/mac_ip_example/mac_ip_example.srcs/sources_1/ip/mac_data_bram/mac_data_bram.xci
# IP: The module: 'mac_data_bram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: i:/rgmii/viv16/mac_ip_example/mac_ip_example.srcs/sources_1/ip/mac_data_bram/mac_data_bram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mac_data_bram'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: i:/rgmii/viv16/mac_ip_example/mac_ip_example.srcs/sources_1/ip/mac_data_bram/mac_data_bram.xci
# IP: The module: 'mac_data_bram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: i:/rgmii/viv16/mac_ip_example/mac_ip_example.srcs/sources_1/ip/mac_data_bram/mac_data_bram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'mac_data_bram'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
