# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a200tfbg676-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir i:/rgmii/viv16/mac_ip_example/mac_ip_example.cache/wt [current_project]
set_property parent.project_path i:/rgmii/viv16/mac_ip_example/mac_ip_example.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part xilinx.com:ac701:part0:1.3 [current_project]
read_ip -quiet i:/rgmii/viv16/mac_ip_example/mac_ip_example.srcs/sources_1/ip/mac_data_bram/mac_data_bram.xci
set_property is_locked true [get_files i:/rgmii/viv16/mac_ip_example/mac_ip_example.srcs/sources_1/ip/mac_data_bram/mac_data_bram.xci]

foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top mac_data_bram -part xc7a200tfbg676-2 -mode out_of_context

rename_ref -prefix_all mac_data_bram_

write_checkpoint -force -noxdef mac_data_bram.dcp

catch { report_utilization -file mac_data_bram_utilization_synth.rpt -pb mac_data_bram_utilization_synth.pb }

if { [catch {
  file copy -force i:/rgmii/viv16/mac_ip_example/mac_ip_example.runs/mac_data_bram_synth_1/mac_data_bram.dcp i:/rgmii/viv16/mac_ip_example/mac_ip_example.srcs/sources_1/ip/mac_data_bram/mac_data_bram.dcp
} _RESULT ] } { 
  send_msg_id runtcl-3 error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
  error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
}

if { [catch {
  write_verilog -force -mode synth_stub i:/rgmii/viv16/mac_ip_example/mac_ip_example.srcs/sources_1/ip/mac_data_bram/mac_data_bram_stub.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a Verilog synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  write_vhdl -force -mode synth_stub i:/rgmii/viv16/mac_ip_example/mac_ip_example.srcs/sources_1/ip/mac_data_bram/mac_data_bram_stub.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a VHDL synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  write_verilog -force -mode funcsim i:/rgmii/viv16/mac_ip_example/mac_ip_example.srcs/sources_1/ip/mac_data_bram/mac_data_bram_sim_netlist.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the Verilog functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

if { [catch {
  write_vhdl -force -mode funcsim i:/rgmii/viv16/mac_ip_example/mac_ip_example.srcs/sources_1/ip/mac_data_bram/mac_data_bram_sim_netlist.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the VHDL functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

if {[file isdir i:/rgmii/viv16/mac_ip_example/mac_ip_example.ip_user_files/ip/mac_data_bram]} {
  catch { 
    file copy -force i:/rgmii/viv16/mac_ip_example/mac_ip_example.srcs/sources_1/ip/mac_data_bram/mac_data_bram_stub.v i:/rgmii/viv16/mac_ip_example/mac_ip_example.ip_user_files/ip/mac_data_bram
  }
}

if {[file isdir i:/rgmii/viv16/mac_ip_example/mac_ip_example.ip_user_files/ip/mac_data_bram]} {
  catch { 
    file copy -force i:/rgmii/viv16/mac_ip_example/mac_ip_example.srcs/sources_1/ip/mac_data_bram/mac_data_bram_stub.vhdl i:/rgmii/viv16/mac_ip_example/mac_ip_example.ip_user_files/ip/mac_data_bram
  }
}
