




set_property IOSTANDARD LVDS_25 [get_ports sma_clk_p]

set_property PACKAGE_PIN J23 [get_ports sma_clk_p]
set_property PACKAGE_PIN H23 [get_ports sma_clk_n]
set_property IOSTANDARD LVDS_25 [get_ports sma_clk_n]
########## GENERAL PIN CONSTRAINTS FOR THE AC701 BOARD REV B for RGMII ##########
set_property PACKAGE_PIN R3 [get_ports clk_in_p]
set_property PACKAGE_PIN P3 [get_ports clk_in_n]
set_property IOSTANDARD DIFF_SSTL15 [get_ports clk_in_p]
set_property IOSTANDARD DIFF_SSTL15 [get_ports clk_in_n]

set_property PACKAGE_PIN U4 [get_ports glbl_rst]
set_property IOSTANDARD SSTL15 [get_ports glbl_rst]
set_false_path -from [get_ports glbl_rst]



set_property PACKAGE_PIN V18 [get_ports phy_resetn]
set_property IOSTANDARD HSTL_I_18 [get_ports phy_resetn]



set_property PACKAGE_PIN W18 [get_ports mdc]
set_property PACKAGE_PIN T14 [get_ports mdio]
set_property IOSTANDARD LVCMOS18 [get_ports mdc]
set_property IOSTANDARD LVCMOS18 [get_ports mdio]

set_property PACKAGE_PIN V14 [get_ports {rgmii_rxd[3]}]
set_property PACKAGE_PIN V16 [get_ports {rgmii_rxd[2]}]
set_property PACKAGE_PIN V17 [get_ports {rgmii_rxd[1]}]
set_property PACKAGE_PIN U17 [get_ports {rgmii_rxd[0]}]
set_property IOSTANDARD HSTL_I_18 [get_ports {rgmii_rxd[3]}]
set_property IOSTANDARD HSTL_I_18 [get_ports {rgmii_rxd[2]}]
set_property IOSTANDARD HSTL_I_18 [get_ports {rgmii_rxd[1]}]
set_property IOSTANDARD HSTL_I_18 [get_ports {rgmii_rxd[0]}]

set_property PACKAGE_PIN T17 [get_ports {rgmii_txd[3]}]
set_property PACKAGE_PIN T18 [get_ports {rgmii_txd[2]}]
set_property PACKAGE_PIN U15 [get_ports {rgmii_txd[1]}]
set_property PACKAGE_PIN U16 [get_ports {rgmii_txd[0]}]
set_property IOSTANDARD HSTL_I_18 [get_ports {rgmii_txd[3]}]
set_property IOSTANDARD HSTL_I_18 [get_ports {rgmii_txd[2]}]
set_property IOSTANDARD HSTL_I_18 [get_ports {rgmii_txd[1]}]
set_property IOSTANDARD HSTL_I_18 [get_ports {rgmii_txd[0]}]

set_property PACKAGE_PIN T15 [get_ports rgmii_tx_ctl]
set_property PACKAGE_PIN U22 [get_ports rgmii_txc]
set_property IOSTANDARD HSTL_I_18 [get_ports rgmii_tx_ctl]
set_property IOSTANDARD HSTL_I_18 [get_ports rgmii_txc]

set_property PACKAGE_PIN U14 [get_ports rgmii_rx_ctl]
set_property IOSTANDARD HSTL_I_18 [get_ports rgmii_rx_ctl]

set_property PACKAGE_PIN U21 [get_ports rgmii_rxc]
set_property IOSTANDARD HSTL_I_18 [get_ports rgmii_rxc]

set_property INTERNAL_VREF 0.9 [get_iobanks 13]

set_property IODELAY_GROUP tri_mode_ethernet_mac_iodelay_grp [get_cells {trimac_fifo_block/trimac_sup_block/tri_mode_ethernet_mac_idelayctrl_common_i}]


create_clock -period 5.000 -name clk_in_p [get_ports clk_in_p]
set_input_jitter clk_in_p 0.050


set_output_delay -clock [get_clocks -of [get_pins example_clocks/clock_generator/mmcm_adv_inst/CLKOUT1]] 1 [get_ports mdc]

set_false_path -from [get_cells -hier -filter {name =~ *phy_resetn_int_reg}] -to [get_ports phy_resetn]




set_property PACKAGE_PIN D18 [get_ports TX_UT_p]
set_property IOSTANDARD LVCMOS25 [get_ports TX_UT_p]

set_property PACKAGE_PIN H14 [get_ports {RX_UT_p[0]}]
set_property IOSTANDARD LVCMOS25 [get_ports {RX_UT_p[0]}]
set_property PACKAGE_PIN E20 [get_ports {RX_UT_p[1]}]
set_property IOSTANDARD LVCMOS25 [get_ports {RX_UT_p[1]}]
set_property PACKAGE_PIN H15 [get_ports {RX_UT_p[2]}]
set_property IOSTANDARD LVCMOS25 [get_ports {RX_UT_p[2]}]
set_property PACKAGE_PIN D20 [get_ports {RX_UT_p[3]}]
set_property IOSTANDARD LVCMOS25 [get_ports {RX_UT_p[3]}]


set_property PACKAGE_PIN G17 [get_ports {PCPU100u_DUT[0]}]
set_property IOSTANDARD LVCMOS25 [get_ports {PCPU100u_DUT[0]}]
set_property PACKAGE_PIN A20 [get_ports {PCPU100u_DUT[1]}]
set_property IOSTANDARD LVCMOS25 [get_ports {PCPU100u_DUT[1]}]
set_property PACKAGE_PIN C21 [get_ports {PCPU100u_DUT[2]}]
set_property IOSTANDARD LVCMOS25 [get_ports {PCPU100u_DUT[2]}]
set_property PACKAGE_PIN B21 [get_ports {PCPU100u_DUT[3]}]
set_property IOSTANDARD LVCMOS25 [get_ports {PCPU100u_DUT[3]}]

set_property PACKAGE_PIN B20 [get_ports {PCPU100u_DUTq[0]}]
set_property IOSTANDARD LVCMOS25 [get_ports {PCPU100u_DUTq[0]}]
set_property PACKAGE_PIN F18 [get_ports {PCPU100u_DUTq[1]}]
set_property IOSTANDARD LVCMOS25 [get_ports {PCPU100u_DUTq[1]}]
set_property PACKAGE_PIN F19 [get_ports {PCPU100u_DUTq[2]}]
set_property IOSTANDARD LVCMOS25 [get_ports {PCPU100u_DUTq[2]}]
set_property PACKAGE_PIN G15 [get_ports {PCPU100u_DUTq[3]}]
set_property IOSTANDARD LVCMOS25 [get_ports {PCPU100u_DUTq[3]}]


set_property PACKAGE_PIN H16 [get_ports {PCPU_status[0]}]
set_property IOSTANDARD LVCMOS25 [get_ports {PCPU_status[0]}]
set_property PACKAGE_PIN K21 [get_ports {PCPU_status[1]}]
set_property IOSTANDARD LVCMOS25 [get_ports {PCPU_status[1]}]
set_property PACKAGE_PIN G16 [get_ports {PCPU_status[2]}]
set_property IOSTANDARD LVCMOS25 [get_ports {PCPU_status[2]}]
set_property PACKAGE_PIN J21 [get_ports {PCPU_status[3]}]
set_property IOSTANDARD LVCMOS25 [get_ports {PCPU_status[3]}]


set_property PACKAGE_PIN B22 [get_ports {Monitor_enable[0]}]
set_property IOSTANDARD LVCMOS25 [get_ports {Monitor_enable[0]}]
set_property PACKAGE_PIN F15 [get_ports {Monitor_enable[1]}]
set_property IOSTANDARD LVCMOS25 [get_ports {Monitor_enable[1]}]
set_property PACKAGE_PIN A22 [get_ports {Monitor_enable[2]}]
set_property IOSTANDARD LVCMOS25 [get_ports {Monitor_enable[2]}]
set_property PACKAGE_PIN G19 [get_ports {Monitor_enable[3]}]
set_property IOSTANDARD LVCMOS25 [get_ports {Monitor_enable[3]}]





set_property PACKAGE_PIN E18 [get_ports DUT_RESET_P]
set_property IOSTANDARD LVCMOS25 [get_ports DUT_RESET_P]

set_property PACKAGE_PIN A19 [get_ports TX_RF_PULSE_V]
set_property IOSTANDARD LVCMOS25 [get_ports TX_RF_PULSE_V]




set_property PACKAGE_PIN E25 [get_ports TX_Win_Pulse]
set_property IOSTANDARD LVCMOS25 [get_ports TX_Win_Pulse]

set_property PACKAGE_PIN K23 [get_ports pna_copy_sig]
set_property IOSTANDARD LVCMOS25 [get_ports pna_copy_sig]

set_property PACKAGE_PIN D25 [get_ports pna_copy2_sig]
set_property IOSTANDARD LVCMOS25 [get_ports pna_copy2_sig]


set_property PACKAGE_PIN A17 [get_ports TX_PRE_SEL_P]
set_property IOSTANDARD LVCMOS25 [get_ports TX_PRE_SEL_P]

set_property PACKAGE_PIN C18 [get_ports TX_RF_PULSE_P]
set_property IOSTANDARD LVCMOS25 [get_ports TX_RF_PULSE_P]

set_property PACKAGE_PIN E17 [get_ports TX_BEAM_INI_P]
set_property IOSTANDARD LVCMOS25 [get_ports TX_BEAM_INI_P]

set_property PACKAGE_PIN A18 [get_ports RX_DATA_WIN_P]
set_property IOSTANDARD LVCMOS25 [get_ports RX_DATA_WIN_P]

set_property PACKAGE_PIN B19 [get_ports TX_BEAM_HOP_P]
set_property IOSTANDARD LVCMOS25 [get_ports TX_BEAM_HOP_P]


set_property PACKAGE_PIN E16 [get_ports self_preselect]
set_property IOSTANDARD LVCMOS25 [get_ports self_preselect]

set_property PACKAGE_PIN M14 [get_ports self_tx_pulse_h]
set_property IOSTANDARD LVCMOS25 [get_ports self_tx_pulse_h]

set_property PACKAGE_PIN D16 [get_ports self_data_window]
set_property IOSTANDARD LVCMOS25 [get_ports self_data_window]

set_property PACKAGE_PIN L14 [get_ports self_beam_ini]
set_property IOSTANDARD LVCMOS25 [get_ports self_beam_ini]

set_property PACKAGE_PIN M16 [get_ports self_beam_hop]
set_property IOSTANDARD LVCMOS25 [get_ports self_beam_hop]

set_property PACKAGE_PIN J18 [get_ports self_test_reset]
set_property IOSTANDARD LVCMOS25 [get_ports self_test_reset]

set_property PACKAGE_PIN M17 [get_ports self_tx_pulse_v]
set_property IOSTANDARD LVCMOS25 [get_ports self_tx_pulse_v]

set_property PACKAGE_PIN J19 [get_ports {self_test_PCPU100u[0]}]
set_property IOSTANDARD LVCMOS25 [get_ports {self_test_PCPU100u[0]}]

set_property PACKAGE_PIN G22 [get_ports {self_test_PCPU100u[1]}]
set_property IOSTANDARD LVCMOS25 [get_ports {self_test_PCPU100u[1]}]

set_property PACKAGE_PIN F22 [get_ports {self_test_PCPU100u[2]}]
set_property IOSTANDARD LVCMOS25 [get_ports {self_test_PCPU100u[2]}]

set_property PACKAGE_PIN L17 [get_ports {self_test_PCPU100u[3]}]
set_property IOSTANDARD LVCMOS25 [get_ports {self_test_PCPU100u[3]}]

set_property PACKAGE_PIN J24 [get_ports {self_test_PCPU100u[4]}]
set_property IOSTANDARD LVCMOS25 [get_ports {self_test_PCPU100u[4]}]

set_property PACKAGE_PIN L18 [get_ports {self_test_PCPU100u[5]}]
set_property IOSTANDARD LVCMOS25 [get_ports {self_test_PCPU100u[5]}]

set_property PACKAGE_PIN H24 [get_ports {self_test_PCPU100u[6]}]
set_property IOSTANDARD LVCMOS25 [get_ports {self_test_PCPU100u[6]}]

set_property PACKAGE_PIN K20 [get_ports {self_test_PCPU100u[7]}]
set_property IOSTANDARD LVCMOS25 [get_ports {self_test_PCPU100u[7]}]

#set_property    PACKAGE_PIN H19 [get_ports self_test_sync_signal]
#set_property IOSTANDARD LVCMOS25 [get_ports sync_signal]

#set_property    PACKAGE_PIN F17 [get_ports sync_signal]
#set_property IOSTANDARD LVCMOS25 [get_ports sync_signal]

set_property MARK_DEBUG false [get_nets {U3/DIN_ESB_s[0]}]
set_property MARK_DEBUG false [get_nets {U3/DIN_ESB_s[1]}]
set_property MARK_DEBUG false [get_nets {U3/DIN_ESB_s[2]}]
set_property MARK_DEBUG false [get_nets {U3/DIN_ESB_s[3]}]
set_property MARK_DEBUG false [get_nets {U3/DIN_ESB_s[4]}]
set_property MARK_DEBUG false [get_nets {U3/DIN_ESB_s[5]}]
set_property MARK_DEBUG false [get_nets {U3/DIN_ESB_s[6]}]
set_property MARK_DEBUG false [get_nets {U3/DIN_ESB_s[7]}]
set_property MARK_DEBUG false [get_nets {U3/cmd_id_DUT_num[2]}]
set_property MARK_DEBUG false [get_nets {U3/cmd_id_DUT_num[3]}]
set_property MARK_DEBUG false [get_nets {U3/len_frame_byt[0]}]
set_property MARK_DEBUG false [get_nets {U3/len_frame_byt[1]}]
set_property MARK_DEBUG false [get_nets {U3/len_frame_byt[2]}]
set_property MARK_DEBUG false [get_nets {U3/len_frame_byt[3]}]
set_property MARK_DEBUG false [get_nets {U3/len_frame_byt[4]}]
set_property MARK_DEBUG false [get_nets {U3/len_frame_byt[5]}]
set_property MARK_DEBUG false [get_nets {U3/len_frame_byt[6]}]
set_property MARK_DEBUG false [get_nets {U3/len_frame_byt[7]}]
set_property MARK_DEBUG false [get_nets {U3/len_frame_byt_rx[0]}]
set_property MARK_DEBUG false [get_nets {U3/len_frame_byt_rx[1]}]
set_property MARK_DEBUG false [get_nets {U3/len_frame_byt_rx[2]}]
set_property MARK_DEBUG false [get_nets {U3/len_frame_byt_rx[3]}]
set_property MARK_DEBUG false [get_nets {U3/len_frame_byt_rx[4]}]
set_property MARK_DEBUG false [get_nets {U3/len_frame_byt_rx[5]}]
set_property MARK_DEBUG false [get_nets {U3/len_frame_byt_rx[6]}]
set_property MARK_DEBUG false [get_nets {U3/len_frame_byt_rx[7]}]
set_property MARK_DEBUG false [get_nets {U3/PCPU100u_DUT[0]}]
set_property MARK_DEBUG false [get_nets {U3/PCPU100u_DUT[1]}]
set_property MARK_DEBUG false [get_nets {U3/PCPU100u_DUT[2]}]
set_property MARK_DEBUG false [get_nets {U3/PCPU100u_DUT[3]}]
set_property MARK_DEBUG false [get_nets {U3/PCPU100u_dutq[0]}]
set_property MARK_DEBUG false [get_nets {U3/PCPU100u_dutq[1]}]
set_property MARK_DEBUG false [get_nets {U3/PCPU100u_dutq[2]}]
set_property MARK_DEBUG false [get_nets {U3/PCPU100u_dutq[3]}]
set_property MARK_DEBUG false [get_nets {U3/monitor_enable[1]}]
set_property MARK_DEBUG false [get_nets {U3/monitor_enable[2]}]
set_property MARK_DEBUG false [get_nets {U3/monitor_enable[3]}]
set_property MARK_DEBUG false [get_nets {U4/RX_IN_p[1]}]
set_property MARK_DEBUG false [get_nets {U4/RX_IN_p[2]}]
set_property MARK_DEBUG false [get_nets {U4/RX_IN_p[3]}]
set_property MARK_DEBUG false [get_nets {U4/U1_UMC/uart_rx_ctl_i0/ce_name/dout[15]}]
set_property MARK_DEBUG false [get_nets {U4/U1_UMC/uart_rx_ctl_i0/ce_name/dout[14]}]
set_property MARK_DEBUG false [get_nets {U4/U1_UMC/uart_rx_ctl_i0/ce_name/dout[13]}]
set_property MARK_DEBUG false [get_nets {U4/U1_UMC/uart_rx_ctl_i0/ce_name/dout[12]}]
set_property MARK_DEBUG false [get_nets {U4/U1_UMC/uart_rx_ctl_i0/ce_name/dout[9]}]
set_property MARK_DEBUG false [get_nets {U4/U1_UMC/uart_rx_ctl_i0/ce_name/dout[11]}]
set_property MARK_DEBUG false [get_nets {U4/U1_UMC/uart_rx_ctl_i0/ce_name/dout[8]}]
set_property MARK_DEBUG false [get_nets {U4/U1_UMC/uart_rx_ctl_i0/ce_name/dout[10]}]




set_property MARK_DEBUG false [get_nets U3/PCPU100u_sig2]
set_property MARK_DEBUG false [get_nets {U3/cmd_id_DUT_num[0]}]
set_property MARK_DEBUG false [get_nets {U3/cmd_id_DUT_num[1]}]
set_property MARK_DEBUG false [get_nets {U3/count_addr_Q[0]}]
set_property MARK_DEBUG false [get_nets {U3/count_addr_Q[1]}]
set_property MARK_DEBUG false [get_nets {U3/count_addr_Q[2]}]
set_property MARK_DEBUG false [get_nets {U3/count_addr_Q[3]}]
set_property MARK_DEBUG false [get_nets {U3/count_addr_Q[4]}]
set_property MARK_DEBUG false [get_nets {U3/count_addr_Q[5]}]
set_property MARK_DEBUG false [get_nets {U3/count_addr_Q[6]}]
set_property MARK_DEBUG false [get_nets {U3/data_bram_out[0]}]
set_property MARK_DEBUG false [get_nets {U3/data_bram_out[1]}]
set_property MARK_DEBUG false [get_nets {U3/data_bram_out[2]}]
set_property MARK_DEBUG false [get_nets {U3/data_bram_out[3]}]
set_property MARK_DEBUG false [get_nets {U3/data_bram_out[4]}]
set_property MARK_DEBUG false [get_nets {U3/data_bram_out[5]}]
set_property MARK_DEBUG false [get_nets {U3/data_bram_out[6]}]
set_property MARK_DEBUG false [get_nets {U3/data_bram_out[7]}]
set_property MARK_DEBUG false [get_nets {U3/enable_pcpu_rd_status[0]}]
set_property MARK_DEBUG false [get_nets {U3/enable_pcpu_rd_status[1]}]
set_property MARK_DEBUG false [get_nets {U3/enable_pcpu_rd_status[2]}]
set_property MARK_DEBUG false [get_nets {U3/enable_pcpu_rd_status[3]}]
set_property MARK_DEBUG false [get_nets U3/gen_pcpu_mod2]
set_property MARK_DEBUG false [get_nets {U3/valid_uart[0]}]
set_property MARK_DEBUG false [get_nets {U3/valid_uart[1]}]
set_property MARK_DEBUG false [get_nets {U3/valid_uart[2]}]
set_property MARK_DEBUG false [get_nets {U3/valid_uart[3]}]
set_property MARK_DEBUG false [get_nets {U4/DOUT_UMC[0]}]
set_property MARK_DEBUG false [get_nets {U4/DOUT_UMC[1]}]
set_property MARK_DEBUG false [get_nets {U4/DOUT_UMC[2]}]
set_property MARK_DEBUG false [get_nets {U4/DOUT_UMC[3]}]
set_property MARK_DEBUG false [get_nets {U4/DOUT_UMC[4]}]
set_property MARK_DEBUG false [get_nets {U4/DOUT_UMC[5]}]
set_property MARK_DEBUG false [get_nets {U4/DOUT_UMC[6]}]
set_property MARK_DEBUG false [get_nets {U4/DOUT_UMC[7]}]
set_property MARK_DEBUG false [get_nets U4/Data_Valid_UMC]
set_property MARK_DEBUG false [get_nets {mac1/tx_axis_fifo_tdata[0]}]
set_property MARK_DEBUG false [get_nets {mac1/tx_axis_fifo_tdata[1]}]
set_property MARK_DEBUG false [get_nets {mac1/tx_axis_fifo_tdata[2]}]
set_property MARK_DEBUG false [get_nets {mac1/tx_axis_fifo_tdata[3]}]
set_property MARK_DEBUG false [get_nets {mac1/tx_axis_fifo_tdata[4]}]
set_property MARK_DEBUG false [get_nets {mac1/tx_axis_fifo_tdata[5]}]
set_property MARK_DEBUG false [get_nets {mac1/tx_axis_fifo_tdata[6]}]
set_property MARK_DEBUG false [get_nets {mac1/tx_axis_fifo_tdata[7]}]
set_property MARK_DEBUG false [get_nets mac1/tx_axis_fifo_tlast]
set_property MARK_DEBUG false [get_nets mac1/tx_axis_fifo_tready]
set_property MARK_DEBUG false [get_nets mac1/tx_axis_fifo_tvalid]




set_property MARK_DEBUG true [get_nets {U4/Us_UMC/U0_MSc/valid_out_s[0]}]
set_property MARK_DEBUG false [get_nets {U4/Us_UMC/U0_MSc/valid_out_s[2]}]
set_property MARK_DEBUG false [get_nets {U4/Us_UMC/U0_MSc/valid_out_s[3]}]
set_property MARK_DEBUG false [get_nets {U4/Us_UMC/U0_MSc/valid_out_s[1]}]
connect_debug_port u_ila_0/probe4 [get_nets [list {U4/Us_UMC/U0_MSc/valid_out_s[0]}]]



set_property MARK_DEBUG false [get_nets {U4/U1_UMC/uart_rx_ctl_i0/bit_samples[6]}]
set_property MARK_DEBUG false [get_nets {U4/U1_UMC/uart_rx_ctl_i0/bit_samples[3]}]
set_property MARK_DEBUG false [get_nets {U4/U1_UMC/uart_rx_ctl_i0/bit_samples[49]}]
set_property MARK_DEBUG false [get_nets {U4/U1_UMC/uart_rx_ctl_i0/bit_samples[4]}]
set_property MARK_DEBUG false [get_nets {U4/U1_UMC/uart_rx_ctl_i0/bit_samples[50]}]
set_property MARK_DEBUG false [get_nets {U4/U1_UMC/uart_rx_ctl_i0/bit_samples[5]}]
set_property MARK_DEBUG false [get_nets {U4/U1_UMC/uart_rx_ctl_i0/bit_samples[51]}]
set_property MARK_DEBUG false [get_nets {U4/U1_UMC/uart_rx_ctl_i0/bit_samples[7]}]
set_property MARK_DEBUG false [get_nets {U4/U1_UMC/uart_rx_ctl_i0/bit_samples[8]}]
set_property MARK_DEBUG false [get_nets {U4/U1_UMC/uart_rx_ctl_i0/bit_samples[11]}]
set_property MARK_DEBUG false [get_nets {U4/U1_UMC/uart_rx_ctl_i0/bit_samples[10]}]
set_property MARK_DEBUG false [get_nets {U4/U1_UMC/uart_rx_ctl_i0/bit_samples[12]}]
set_property MARK_DEBUG false [get_nets {U4/U1_UMC/uart_rx_ctl_i0/bit_samples[14]}]
set_property MARK_DEBUG false [get_nets {U4/U1_UMC/uart_rx_ctl_i0/bit_samples[9]}]
set_property MARK_DEBUG false [get_nets {U4/U1_UMC/uart_rx_ctl_i0/bit_samples[13]}]
set_property MARK_DEBUG false [get_nets {U4/U1_UMC/uart_rx_ctl_i0/bit_samples[15]}]
set_property MARK_DEBUG false [get_nets {U4/U1_UMC/uart_rx_ctl_i0/bit_samples[16]}]
set_property MARK_DEBUG false [get_nets {U4/U1_UMC/uart_rx_ctl_i0/bit_samples[17]}]
set_property MARK_DEBUG false [get_nets {U4/U1_UMC/uart_rx_ctl_i0/bit_samples[18]}]
set_property MARK_DEBUG false [get_nets {U4/U1_UMC/uart_rx_ctl_i0/bit_samples[19]}]
set_property MARK_DEBUG false [get_nets {U4/U1_UMC/uart_rx_ctl_i0/bit_samples[20]}]
set_property MARK_DEBUG false [get_nets {U4/U1_UMC/uart_rx_ctl_i0/bit_samples[21]}]
set_property MARK_DEBUG false [get_nets {U4/U1_UMC/uart_rx_ctl_i0/bit_samples[22]}]
set_property MARK_DEBUG false [get_nets {U4/U1_UMC/uart_rx_ctl_i0/bit_samples[23]}]
set_property MARK_DEBUG false [get_nets {U4/U1_UMC/uart_rx_ctl_i0/bit_samples[24]}]
set_property MARK_DEBUG false [get_nets {U4/U1_UMC/uart_rx_ctl_i0/bit_samples[25]}]
set_property MARK_DEBUG false [get_nets {U4/U1_UMC/uart_rx_ctl_i0/bit_samples[26]}]
set_property MARK_DEBUG false [get_nets {U4/U1_UMC/uart_rx_ctl_i0/bit_samples[27]}]
set_property MARK_DEBUG false [get_nets {U4/U1_UMC/uart_rx_ctl_i0/bit_samples[28]}]
set_property MARK_DEBUG false [get_nets {U4/U1_UMC/uart_rx_ctl_i0/bit_samples[29]}]
set_property MARK_DEBUG false [get_nets {U4/U1_UMC/uart_rx_ctl_i0/bit_samples[30]}]
set_property MARK_DEBUG false [get_nets {U4/U1_UMC/uart_rx_ctl_i0/bit_samples[31]}]
set_property MARK_DEBUG false [get_nets {U4/U1_UMC/uart_rx_ctl_i0/bit_samples[33]}]
set_property MARK_DEBUG false [get_nets {U4/U1_UMC/uart_rx_ctl_i0/bit_samples[34]}]
set_property MARK_DEBUG false [get_nets {U4/U1_UMC/uart_rx_ctl_i0/bit_samples[35]}]
set_property MARK_DEBUG false [get_nets {U4/U1_UMC/uart_rx_ctl_i0/bit_samples[36]}]
set_property MARK_DEBUG false [get_nets {U4/U1_UMC/uart_rx_ctl_i0/bit_samples[37]}]
set_property MARK_DEBUG false [get_nets {U4/U1_UMC/uart_rx_ctl_i0/bit_samples[38]}]
set_property MARK_DEBUG false [get_nets {U4/U1_UMC/uart_rx_ctl_i0/bit_samples[39]}]
set_property MARK_DEBUG false [get_nets {U4/U1_UMC/uart_rx_ctl_i0/bit_samples[40]}]
set_property MARK_DEBUG false [get_nets {U4/U1_UMC/uart_rx_ctl_i0/bit_samples[41]}]
set_property MARK_DEBUG false [get_nets {U4/U1_UMC/uart_rx_ctl_i0/bit_samples[42]}]
set_property MARK_DEBUG false [get_nets {U4/U1_UMC/uart_rx_ctl_i0/bit_samples[43]}]
set_property MARK_DEBUG false [get_nets {U4/U1_UMC/uart_rx_ctl_i0/bit_samples[44]}]
set_property MARK_DEBUG false [get_nets {U4/U1_UMC/uart_rx_ctl_i0/bit_samples[45]}]
set_property MARK_DEBUG false [get_nets {U4/U1_UMC/uart_rx_ctl_i0/bit_samples[47]}]
set_property MARK_DEBUG false [get_nets {U4/U1_UMC/uart_rx_ctl_i0/bit_samples[2]}]
set_property MARK_DEBUG false [get_nets {U4/U1_UMC/uart_rx_ctl_i0/bit_samples[48]}]
set_property MARK_DEBUG false [get_nets {U4/U1_UMC/uart_rx_ctl_i0/bit_samples[0]}]
set_property MARK_DEBUG false [get_nets {U4/U1_UMC/uart_rx_ctl_i0/bit_samples[1]}]
set_property MARK_DEBUG false [get_nets {U4/U1_UMC/uart_rx_ctl_i0/bit_samples[32]}]
set_property MARK_DEBUG false [get_nets {U4/U1_UMC/uart_rx_ctl_i0/bit_samples[46]}]
set_property MARK_DEBUG false [get_nets {U4/U1_UMC/uart_rx_ctl_i0/sum_samples[22]}]
set_property MARK_DEBUG false [get_nets {U4/U1_UMC/uart_rx_ctl_i0/sum_samples[50]}]
set_property MARK_DEBUG false [get_nets {U4/U1_UMC/uart_rx_ctl_i0/sum_samples[18]}]
set_property MARK_DEBUG false [get_nets {U4/U1_UMC/uart_rx_ctl_i0/sum_samples[26]}]
set_property MARK_DEBUG false [get_nets {U4/U1_UMC/uart_rx_ctl_i0/sum_samples[21]}]
set_property MARK_DEBUG false [get_nets {U4/U1_UMC/uart_rx_ctl_i0/sum_samples[49]}]
set_property MARK_DEBUG false [get_nets {U4/U1_UMC/uart_rx_ctl_i0/sum_samples[17]}]
set_property MARK_DEBUG false [get_nets {U4/U1_UMC/uart_rx_ctl_i0/sum_samples[51]}]
set_property MARK_DEBUG false [get_nets {U4/U1_UMC/uart_rx_ctl_i0/sum_samples[19]}]
set_property MARK_DEBUG false [get_nets {U4/U1_UMC/uart_rx_ctl_i0/sum_samples[23]}]
set_property MARK_DEBUG false [get_nets {U4/U1_UMC/uart_rx_ctl_i0/sum_samples[47]}]
set_property MARK_DEBUG false [get_nets {U4/U1_UMC/uart_rx_ctl_i0/sum_samples[15]}]
set_property MARK_DEBUG false [get_nets {U4/U1_UMC/uart_rx_ctl_i0/sum_samples[20]}]
set_property MARK_DEBUG false [get_nets {U4/U1_UMC/uart_rx_ctl_i0/sum_samples[24]}]
set_property MARK_DEBUG false [get_nets {U4/U1_UMC/uart_rx_ctl_i0/sum_samples[25]}]
set_property MARK_DEBUG false [get_nets {U4/U1_UMC/uart_rx_ctl_i0/sum_samples[27]}]
set_property MARK_DEBUG false [get_nets U4/U1_UMC/uart_rx_ctl_i0/ce_name/valid]
set_property MARK_DEBUG false [get_nets {U4/U1_UMC/uart_rx_ctl_i0/sum_samples[28]}]
set_property MARK_DEBUG false [get_nets {U4/U1_UMC/uart_rx_ctl_i0/sum_samples[29]}]
set_property MARK_DEBUG false [get_nets {U4/U1_UMC/uart_rx_ctl_i0/sum_samples[31]}]
set_property MARK_DEBUG false [get_nets {U4/U1_UMC/uart_rx_ctl_i0/sum_samples[32]}]
set_property MARK_DEBUG false [get_nets {U4/U1_UMC/uart_rx_ctl_i0/ce_name/dout[5]}]
set_property MARK_DEBUG false [get_nets {U4/U1_UMC/uart_rx_ctl_i0/sum_samples[33]}]
set_property MARK_DEBUG false [get_nets {U4/U1_UMC/uart_rx_ctl_i0/sum_samples[30]}]
set_property MARK_DEBUG false [get_nets {U4/U1_UMC/uart_rx_ctl_i0/sum_samples[34]}]
set_property MARK_DEBUG false [get_nets {U4/U1_UMC/uart_rx_ctl_i0/ce_name/dout[7]}]
set_property MARK_DEBUG false [get_nets {U4/U1_UMC/uart_rx_ctl_i0/sum_samples[35]}]
set_property MARK_DEBUG false [get_nets {U4/Us_UMC/U0_MSc/DOUT_WBB[0]}]
set_property MARK_DEBUG false [get_nets {U4/U1_UMC/uart_rx_ctl_i0/ce_name/dout[6]}]
set_property MARK_DEBUG false [get_nets {U4/U1_UMC/uart_rx_ctl_i0/sum_samples[36]}]
set_property MARK_DEBUG false [get_nets {U4/Us_UMC/U0_MSc/DOUT_WBB[1]}]
set_property MARK_DEBUG false [get_nets {U4/U1_UMC/uart_rx_ctl_i0/ce_name/dout[4]}]
set_property MARK_DEBUG false [get_nets {U4/Us_UMC/U0_MSc/U_WR_BB[2].U0_n_36}]
set_property MARK_DEBUG false [get_nets {U4/U1_UMC/uart_rx_ctl_i0/sum_samples[37]}]
set_property MARK_DEBUG false [get_nets {U4/Us_UMC/U0_MSc/DOUT_WBB[2]}]
set_property MARK_DEBUG false [get_nets {U4/U1_UMC/uart_rx_ctl_i0/ce_name/dout[3]}]
set_property MARK_DEBUG false [get_nets U4/Us_UMC/U0_MSc/n_0_0]
set_property MARK_DEBUG false [get_nets {U4/U1_UMC/uart_rx_ctl_i0/sum_samples[38]}]
set_property MARK_DEBUG false [get_nets {U4/Us_UMC/U0_MSc/DOUT_WBB[3]}]
set_property MARK_DEBUG false [get_nets {U4/U1_UMC/uart_rx_ctl_i0/ce_name/dout[2]}]
set_property MARK_DEBUG false [get_nets U4/Us_UMC/U0_MSc/valid_out_s]
set_property MARK_DEBUG false [get_nets {U4/U1_UMC/uart_rx_ctl_i0/sum_samples[39]}]
set_property MARK_DEBUG false [get_nets {U4/Us_UMC/U0_MSc/DOUT_WBB[4]}]
set_property MARK_DEBUG false [get_nets {U4/U1_UMC/uart_rx_ctl_i0/ce_name/dout[1]}]
set_property MARK_DEBUG false [get_nets U4/Us_UMC/U0_MSc/valid_out_s1_out]
set_property MARK_DEBUG false [get_nets {U4/U1_UMC/uart_rx_ctl_i0/sum_samples[40]}]
set_property MARK_DEBUG false [get_nets {U4/Us_UMC/U0_MSc/DOUT_WBB[5]}]
set_property MARK_DEBUG false [get_nets {U4/U1_UMC/uart_rx_ctl_i0/ce_name/dout[0]}]
set_property MARK_DEBUG false [get_nets {U4/U1_UMC/uart_rx_ctl_i0/sum_samples[41]}]
set_property MARK_DEBUG false [get_nets {U4/Us_UMC/U0_MSc/DOUT_WBB[6]}]
set_property MARK_DEBUG false [get_nets {U4/U1_UMC/uart_rx_ctl_i0/sum_samples[42]}]
set_property MARK_DEBUG false [get_nets {U4/Us_UMC/U0_MSc/DOUT_WBB[7]}]
set_property MARK_DEBUG false [get_nets {U4/U1_UMC/uart_rx_ctl_i0/sum_samples[43]}]
set_property MARK_DEBUG false [get_nets {U4/U1_UMC/uart_rx_ctl_i0/sum_samples[44]}]
set_property MARK_DEBUG false [get_nets {U4/U1_UMC/uart_rx_ctl_i0/sum_samples[45]}]
set_property MARK_DEBUG false [get_nets {U4/U1_UMC/uart_rx_ctl_i0/sum_samples[46]}]
set_property MARK_DEBUG false [get_nets {U4/U1_UMC/uart_rx_ctl_i0/sum_samples[48]}]
set_property MARK_DEBUG false [get_nets {U4/U1_UMC/uart_rx_ctl_i0/bits_rxd_reg__0[6]}]
set_property MARK_DEBUG false [get_nets {U4/U1_UMC/uart_rx_ctl_i0/bits_rxd_reg__0[7]}]
set_property MARK_DEBUG false [get_nets {U4/U1_UMC/uart_rx_ctl_i0/int_bit_cnt_reg__0[0]}]
set_property MARK_DEBUG false [get_nets {U4/U1_UMC/uart_rx_ctl_i0/int_bit_cnt_reg__0[1]}]
set_property MARK_DEBUG false [get_nets {U4/U1_UMC/uart_rx_ctl_i0/int_bit_cnt_reg__0[2]}]
set_property MARK_DEBUG false [get_nets U4/U1_UMC/uart_rx_ctl_i0/cal_val_rx]
set_property MARK_DEBUG false [get_nets {U4/U1_UMC/uart_rx_ctl_i0/int_bit_cnt_reg__0[3]}]
set_property MARK_DEBUG false [get_nets {U4/U1_UMC/uart_rx_ctl_i0/int_bit_cnt_reg__0[4]}]
set_property MARK_DEBUG false [get_nets U4/U1_UMC/uart_rx_ctl_i0/start_lrd_rx]
set_property MARK_DEBUG false [get_nets {U4/U1_UMC/uart_rx_ctl_i0/rx_data[8]}]
set_property MARK_DEBUG false [get_nets {U4/U1_UMC/uart_rx_ctl_i0/rx_data[11]}]
set_property MARK_DEBUG false [get_nets {U4/U1_UMC/uart_rx_ctl_i0/rx_data[9]}]
set_property MARK_DEBUG false [get_nets {U4/U1_UMC/uart_rx_ctl_i0/rx_data[10]}]
set_property MARK_DEBUG false [get_nets {U4/U1_UMC/uart_rx_ctl_i0/rx_data[12]}]
set_property MARK_DEBUG false [get_nets {U4/U1_UMC/uart_rx_ctl_i0/rx_data[13]}]
set_property MARK_DEBUG false [get_nets {U4/U1_UMC/uart_rx_ctl_i0/rx_data[14]}]
set_property MARK_DEBUG false [get_nets {U4/U1_UMC/uart_rx_ctl_i0/rx_data[15]}]
set_property MARK_DEBUG false [get_nets {U4/U1_UMC/uart_rx_ctl_i0/sum_samples[0]}]
set_property MARK_DEBUG false [get_nets {U4/U1_UMC/uart_rx_ctl_i0/bit_samples_orig[0]}]
set_property MARK_DEBUG false [get_nets {U4/Us_UMC/U0_MSc/FIFO_RD_EN_WBB[1]}]
set_property MARK_DEBUG false [get_nets {U4/Us_UMC/U0_MSc/FIFO_RD_EN_WBB[2]}]
set_property MARK_DEBUG false [get_nets {U4/Us_UMC/U0_MSc/FIFO_RD_EN_WBB[3]}]
set_property MARK_DEBUG false [get_nets {U4/U1_UMC/uart_rx_ctl_i0/bit_samples_orig[1]}]
set_property MARK_DEBUG false [get_nets {U4/U1_UMC/uart_rx_ctl_i0/bit_samples_orig[2]}]
set_property MARK_DEBUG false [get_nets {U4/U1_UMC/uart_rx_ctl_i0/bit_samples_orig[3]}]
set_property MARK_DEBUG false [get_nets {U4/U1_UMC/uart_rx_ctl_i0/bit_samples_orig[5]}]
set_property MARK_DEBUG false [get_nets {U4/U1_UMC/uart_rx_ctl_i0/bit_samples_orig[6]}]
set_property MARK_DEBUG false [get_nets {U4/U1_UMC/uart_rx_ctl_i0/bit_samples_orig[8]}]
set_property MARK_DEBUG false [get_nets {U4/U1_UMC/uart_rx_ctl_i0/bit_samples_orig[4]}]
set_property MARK_DEBUG false [get_nets {U4/U1_UMC/uart_rx_ctl_i0/bit_samples_orig[7]}]
set_property MARK_DEBUG false [get_nets {U4/U1_UMC/uart_rx_ctl_i0/bit_samples_orig[15]}]
set_property MARK_DEBUG false [get_nets {U4/U1_UMC/uart_rx_ctl_i0/bit_samples_orig[16]}]
set_property MARK_DEBUG false [get_nets {U4/U1_UMC/uart_rx_ctl_i0/bit_samples_orig[17]}]
set_property MARK_DEBUG false [get_nets {U4/U1_UMC/uart_rx_ctl_i0/bit_samples_orig[40]}]
set_property MARK_DEBUG false [get_nets {U4/U1_UMC/uart_rx_ctl_i0/bit_samples_orig[41]}]
set_property MARK_DEBUG false [get_nets {U4/U1_UMC/uart_rx_ctl_i0/bit_samples_orig[42]}]
set_property MARK_DEBUG false [get_nets {U4/U1_UMC/uart_rx_ctl_i0/bit_samples_orig[44]}]
set_property MARK_DEBUG false [get_nets {U4/Us_UMC/U0_MSc/FIFO_RD_EN_WBB[0]}]
set_property MARK_DEBUG false [get_nets {U4/U1_UMC/uart_rx_ctl_i0/bits_rxd_reg__0[2]}]
set_property MARK_DEBUG false [get_nets {U4/U1_UMC/uart_rx_ctl_i0/bits_rxd_reg__0[3]}]
set_property MARK_DEBUG false [get_nets {U4/U1_UMC/uart_rx_ctl_i0/bits_rxd_reg__0[5]}]
set_property MARK_DEBUG false [get_nets {U4/U1_UMC/uart_rx_ctl_i0/bit_samples_orig[43]}]
set_property MARK_DEBUG false [get_nets {U4/U1_UMC/uart_rx_ctl_i0/bit_samples_orig[46]}]
set_property MARK_DEBUG false [get_nets {U4/U1_UMC/uart_rx_ctl_i0/bit_samples_orig[47]}]
set_property MARK_DEBUG false [get_nets {U4/U1_UMC/uart_rx_ctl_i0/bit_samples_orig[49]}]
set_property MARK_DEBUG false [get_nets {U4/U1_UMC/uart_rx_ctl_i0/bit_samples_orig[45]}]
set_property MARK_DEBUG false [get_nets {U4/U1_UMC/uart_rx_ctl_i0/bit_samples_orig[48]}]
set_property MARK_DEBUG false [get_nets {U4/U1_UMC/uart_rx_ctl_i0/bit_samples_orig[50]}]
set_property MARK_DEBUG false [get_nets {U4/U1_UMC/uart_rx_ctl_i0/bit_samples_orig[51]}]
set_property MARK_DEBUG false [get_nets {U4/U1_UMC/uart_rx_ctl_i0/bits_rxd_reg__0[0]}]
set_property MARK_DEBUG false [get_nets {U4/U1_UMC/uart_rx_ctl_i0/bits_rxd_reg__0[1]}]
set_property MARK_DEBUG false [get_nets {U4/U1_UMC/uart_rx_ctl_i0/sum_samples[1]}]
set_property MARK_DEBUG false [get_nets {U4/U1_UMC/uart_rx_ctl_i0/sum_samples[2]}]
set_property MARK_DEBUG false [get_nets {U4/U1_UMC/uart_rx_ctl_i0/sum_samples[3]}]
set_property MARK_DEBUG false [get_nets {U4/U1_UMC/uart_rx_ctl_i0/sum_samples[4]}]
set_property MARK_DEBUG false [get_nets {U4/U1_UMC/uart_rx_ctl_i0/sum_samples[5]}]
set_property MARK_DEBUG false [get_nets {U4/U1_UMC/uart_rx_ctl_i0/sum_samples[6]}]
set_property MARK_DEBUG false [get_nets {U4/U1_UMC/uart_rx_ctl_i0/sum_samples[7]}]
set_property MARK_DEBUG false [get_nets {U4/U1_UMC/uart_rx_ctl_i0/sum_samples[8]}]
set_property MARK_DEBUG false [get_nets {U4/U1_UMC/uart_rx_ctl_i0/sum_samples[11]}]
set_property MARK_DEBUG false [get_nets {U4/U1_UMC/uart_rx_ctl_i0/sum_samples[9]}]
set_property MARK_DEBUG false [get_nets {U4/U1_UMC/uart_rx_ctl_i0/sum_samples[10]}]
set_property MARK_DEBUG false [get_nets {U4/U1_UMC/uart_rx_ctl_i0/sum_samples[12]}]
set_property MARK_DEBUG false [get_nets {U4/U1_UMC/uart_rx_ctl_i0/sum_samples[13]}]
set_property MARK_DEBUG false [get_nets {U4/U1_UMC/uart_rx_ctl_i0/sum_samples[14]}]
set_property MARK_DEBUG false [get_nets {U4/U1_UMC/uart_rx_ctl_i0/sum_samples[16]}]
set_property MARK_DEBUG false [get_nets {U4/U1_UMC/uart_rx_ctl_i0/bit_samples_orig[39]}]
set_property MARK_DEBUG false [get_nets {U4/U1_UMC/uart_rx_ctl_i0/bit_samples_orig[10]}]
set_property MARK_DEBUG false [get_nets {U4/U1_UMC/uart_rx_ctl_i0/bit_samples_orig[11]}]
set_property MARK_DEBUG false [get_nets {U4/U1_UMC/uart_rx_ctl_i0/bit_samples_orig[12]}]
set_property MARK_DEBUG false [get_nets {U4/U1_UMC/uart_rx_ctl_i0/bit_samples_orig[13]}]
set_property MARK_DEBUG false [get_nets {U4/U1_UMC/uart_rx_ctl_i0/bit_samples_orig[14]}]
set_property MARK_DEBUG false [get_nets {U4/U1_UMC/uart_rx_ctl_i0/bit_samples_orig[18]}]
set_property MARK_DEBUG false [get_nets {U4/U1_UMC/uart_rx_ctl_i0/bit_samples_orig[19]}]
set_property MARK_DEBUG false [get_nets {U4/U1_UMC/uart_rx_ctl_i0/bit_samples_orig[20]}]
set_property MARK_DEBUG false [get_nets {U4/U1_UMC/uart_rx_ctl_i0/bit_samples_orig[21]}]
set_property MARK_DEBUG false [get_nets {U4/U1_UMC/uart_rx_ctl_i0/bit_samples_orig[22]}]
set_property MARK_DEBUG false [get_nets {U4/U1_UMC/uart_rx_ctl_i0/bit_samples_orig[23]}]
set_property MARK_DEBUG false [get_nets {U4/U1_UMC/uart_rx_ctl_i0/bit_samples_orig[24]}]
set_property MARK_DEBUG false [get_nets {U4/U1_UMC/uart_rx_ctl_i0/bit_samples_orig[25]}]
set_property MARK_DEBUG false [get_nets {U4/U1_UMC/uart_rx_ctl_i0/bit_samples_orig[26]}]
set_property MARK_DEBUG false [get_nets {U4/U1_UMC/uart_rx_ctl_i0/bit_samples_orig[27]}]
set_property MARK_DEBUG false [get_nets {U4/U1_UMC/uart_rx_ctl_i0/bit_samples_orig[28]}]
set_property MARK_DEBUG false [get_nets {U4/U1_UMC/uart_rx_ctl_i0/bit_samples_orig[29]}]
set_property MARK_DEBUG false [get_nets {U4/U1_UMC/uart_rx_ctl_i0/bit_samples_orig[30]}]
set_property MARK_DEBUG false [get_nets {U4/U1_UMC/uart_rx_ctl_i0/bit_samples_orig[31]}]
set_property MARK_DEBUG false [get_nets {U4/U1_UMC/uart_rx_ctl_i0/bit_samples_orig[32]}]
set_property MARK_DEBUG false [get_nets {U4/U1_UMC/uart_rx_ctl_i0/bit_samples_orig[33]}]
set_property MARK_DEBUG false [get_nets {U4/U1_UMC/uart_rx_ctl_i0/bit_samples_orig[34]}]
set_property MARK_DEBUG false [get_nets {U4/U1_UMC/uart_rx_ctl_i0/bit_samples_orig[35]}]
set_property MARK_DEBUG false [get_nets {U4/U1_UMC/uart_rx_ctl_i0/bit_samples_orig[36]}]
set_property MARK_DEBUG false [get_nets {U4/U1_UMC/uart_rx_ctl_i0/bit_samples_orig[37]}]
set_property MARK_DEBUG false [get_nets {U4/U1_UMC/uart_rx_ctl_i0/bit_samples_orig[38]}]
set_property MARK_DEBUG false [get_nets {U4/U1_UMC/uart_rx_ctl_i0/bit_samples_orig[9]}]
set_property MARK_DEBUG false [get_nets U4/U1_UMC/uart_rx_ctl_i0/bit_value]
set_property MARK_DEBUG false [get_nets {U4/U1_UMC/uart_rx_ctl_i0/bits_rxd_reg__0[4]}]


set_property MARK_DEBUG false [get_nets {U4/Us_UMC/LEN_PLD_wrb[4]}]
set_property MARK_DEBUG false [get_nets {U4/Us_UMC/LEN_PLD_wrb[1]}]
set_property MARK_DEBUG false [get_nets {U4/Us_UMC/LEN_PLD_wrb[2]}]
set_property MARK_DEBUG false [get_nets {U4/Us_UMC/LEN_PLD_wrb[3]}]
set_property MARK_DEBUG false [get_nets {U4/Us_UMC/LEN_PLD_wrb[5]}]
set_property MARK_DEBUG false [get_nets {U4/Us_UMC/LEN_PLD_wrb[0]}]
set_property MARK_DEBUG false [get_nets {U4/Us_UMC/LEN_PLD_wrb[6]}]
set_property MARK_DEBUG false [get_nets {U4/Us_UMC/LEN_PLD_wrb[7]}]
set_property MARK_DEBUG false [get_nets {U5/data_out[0]}]
set_property MARK_DEBUG false [get_nets {U5/data_out[1]}]
set_property MARK_DEBUG false [get_nets {U5/data_out[2]}]
set_property MARK_DEBUG false [get_nets {U5/data_out[3]}]
set_property MARK_DEBUG false [get_nets U5/mac_data_out_valid]
set_property MARK_DEBUG false [get_nets {U5/data_out[4]}]
set_property MARK_DEBUG false [get_nets {U5/data_out[5]}]
set_property MARK_DEBUG false [get_nets {U5/data_out[6]}]
set_property MARK_DEBUG false [get_nets {U4/Us_UMC/wait_count[0]}]
set_property MARK_DEBUG false [get_nets {U5/data_out[7]}]
set_property MARK_DEBUG false [get_nets {U4/Us_UMC/wait_count[1]}]
set_property MARK_DEBUG false [get_nets {U5/mac_data_out[0]}]
set_property MARK_DEBUG false [get_nets {U5/mac_data_out[1]}]
set_property MARK_DEBUG false [get_nets {U5/mac_data_out[2]}]
set_property MARK_DEBUG false [get_nets {U5/mac_data_out[3]}]
set_property MARK_DEBUG false [get_nets {U5/mac_data_out[4]}]
set_property MARK_DEBUG false [get_nets {U5/mac_data_out[5]}]
set_property MARK_DEBUG false [get_nets {U5/mac_data_out[6]}]
set_property MARK_DEBUG false [get_nets {U5/mac_data_out[7]}]
set_property MARK_DEBUG false [get_nets U5/tx_start]
set_property MARK_DEBUG false [get_nets U4/U1_UMC/uart_rx_ctl_i0/rx_data_rdy]
set_property MARK_DEBUG false [get_nets U4/Us_UMC/rd_en_count]
set_property MARK_DEBUG false [get_nets {U4/Us_UMC/wait_count[8]}]
set_property MARK_DEBUG false [get_nets {U4/Us_UMC/wait_count[11]}]
set_property MARK_DEBUG false [get_nets {U4/Us_UMC/wait_count[9]}]
set_property MARK_DEBUG false [get_nets {U4/Us_UMC/wait_count[10]}]
set_property MARK_DEBUG false [get_nets {U4/Us_UMC/wait_count[12]}]
set_property MARK_DEBUG false [get_nets {U4/Us_UMC/wait_count[13]}]
set_property MARK_DEBUG false [get_nets {U4/U1_UMC/uart_rx_ctl_i0/rx_data[0]}]
set_property MARK_DEBUG false [get_nets {U4/U1_UMC/uart_rx_ctl_i0/rx_data[1]}]
set_property MARK_DEBUG false [get_nets {U4/U1_UMC/uart_rx_ctl_i0/rx_data[2]}]
set_property MARK_DEBUG false [get_nets {U4/U1_UMC/uart_rx_ctl_i0/rx_data[3]}]
set_property MARK_DEBUG false [get_nets {U4/U1_UMC/uart_rx_ctl_i0/rx_data[4]}]
set_property MARK_DEBUG false [get_nets {U4/U1_UMC/uart_rx_ctl_i0/rx_data[5]}]
set_property MARK_DEBUG false [get_nets {U4/U1_UMC/uart_rx_ctl_i0/rx_data[6]}]
set_property MARK_DEBUG false [get_nets {U4/U1_UMC/uart_rx_ctl_i0/rx_data[7]}]
set_property MARK_DEBUG false [get_nets {U4/Us_UMC/wait_count[14]}]
set_property MARK_DEBUG false [get_nets {U4/Us_UMC/wait_count[15]}]
set_property MARK_DEBUG false [get_nets {U4/Us_UMC/wait_count[16]}]
set_property MARK_DEBUG false [get_nets {U4/Us_UMC/wait_count[17]}]
set_property MARK_DEBUG false [get_nets {U4/Us_UMC/wait_count[18]}]
set_property MARK_DEBUG false [get_nets {U4/Us_UMC/wait_count[19]}]
set_property MARK_DEBUG false [get_nets {U4/Us_UMC/wait_count[2]}]
set_property MARK_DEBUG false [get_nets {U4/Us_UMC/wait_count[3]}]
set_property MARK_DEBUG false [get_nets {U4/Us_UMC/wait_count[4]}]
set_property MARK_DEBUG false [get_nets {U4/Us_UMC/wait_count[5]}]
set_property MARK_DEBUG false [get_nets {U4/Us_UMC/wait_count[6]}]
set_property MARK_DEBUG false [get_nets {U4/Us_UMC/wait_count[7]}]


set_property MARK_DEBUG true [get_nets U4/U1_UMC/uart_rx_ctl_i0/rxd_clk_rx]
set_property MARK_DEBUG false [get_nets {U3/monitor_enable[0]}]
set_property MARK_DEBUG false [get_nets U3/DOUT_ESB]
set_property MARK_DEBUG false [get_nets {U4/RX_IN_p[0]}]
set_property MARK_DEBUG true [get_nets {U4/U1_UMC/uart_rx_ctl_i0/ce_name/din[7]}]
set_property MARK_DEBUG true [get_nets {U4/U1_UMC/uart_rx_ctl_i0/ce_name/din[6]}]
set_property MARK_DEBUG true [get_nets {U4/U1_UMC/uart_rx_ctl_i0/ce_name/din[4]}]
set_property MARK_DEBUG true [get_nets {U4/U1_UMC/uart_rx_ctl_i0/ce_name/din[2]}]
set_property MARK_DEBUG true [get_nets {U4/U1_UMC/uart_rx_ctl_i0/ce_name/din[5]}]
set_property MARK_DEBUG true [get_nets {U4/U1_UMC/uart_rx_ctl_i0/ce_name/din[3]}]
set_property MARK_DEBUG true [get_nets {U4/U1_UMC/uart_rx_ctl_i0/ce_name/din[1]}]
set_property MARK_DEBUG true [get_nets {U4/U1_UMC/uart_rx_ctl_i0/ce_name/din[0]}]
set_property MARK_DEBUG true [get_nets U4/U1_UMC/uart_rx_ctl_i0/ce_name/wr_en]
set_property MARK_DEBUG false [get_nets {U4/U1_UMC/uart_rx_ctl_i0/ce_name/din[15]}]
set_property MARK_DEBUG false [get_nets {U4/U1_UMC/uart_rx_ctl_i0/ce_name/din[14]}]
set_property MARK_DEBUG false [get_nets {U4/U1_UMC/uart_rx_ctl_i0/ce_name/din[13]}]
set_property MARK_DEBUG false [get_nets {U4/U1_UMC/uart_rx_ctl_i0/ce_name/din[12]}]
set_property MARK_DEBUG false [get_nets {U4/U1_UMC/uart_rx_ctl_i0/ce_name/din[10]}]
set_property MARK_DEBUG false [get_nets {U4/U1_UMC/uart_rx_ctl_i0/ce_name/din[9]}]
set_property MARK_DEBUG false [get_nets {U4/U1_UMC/uart_rx_ctl_i0/ce_name/din[11]}]
set_property MARK_DEBUG false [get_nets {U4/U1_UMC/uart_rx_ctl_i0/ce_name/din[8]}]

create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 4 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER true [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 131072 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL true [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list U3/U1/DCM_100X70/inst/clk_out2]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 8 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {U4/U1_UMC/uart_rx_ctl_i0/ce_name/din[0]} {U4/U1_UMC/uart_rx_ctl_i0/ce_name/din[1]} {U4/U1_UMC/uart_rx_ctl_i0/ce_name/din[2]} {U4/U1_UMC/uart_rx_ctl_i0/ce_name/din[3]} {U4/U1_UMC/uart_rx_ctl_i0/ce_name/din[4]} {U4/U1_UMC/uart_rx_ctl_i0/ce_name/din[5]} {U4/U1_UMC/uart_rx_ctl_i0/ce_name/din[6]} {U4/U1_UMC/uart_rx_ctl_i0/ce_name/din[7]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 1 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list U4/U1_UMC/uart_rx_ctl_i0/rxd_clk_rx]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 1 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list U4/U1_UMC/uart_rx_ctl_i0/ce_name/wr_en]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets u_ila_0_clk_out2]
