# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a200tfbg676-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir I:/ac701_SAC/mac_ip_example.cache/wt [current_project]
set_property parent.project_path I:/ac701_SAC/mac_ip_example.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part xilinx.com:ac701:part0:1.3 [current_project]
read_ip -quiet I:/ac701_SAC/mac_ip_example.srcs/sources_1/ip/dcm_last/dcm_last.xci
set_property is_locked true [get_files I:/ac701_SAC/mac_ip_example.srcs/sources_1/ip/dcm_last/dcm_last.xci]

foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top dcm_last -part xc7a200tfbg676-2 -mode out_of_context

rename_ref -prefix_all dcm_last_

write_checkpoint -force -noxdef dcm_last.dcp

catch { report_utilization -file dcm_last_utilization_synth.rpt -pb dcm_last_utilization_synth.pb }

if { [catch {
  file copy -force I:/ac701_SAC/mac_ip_example.runs/dcm_last_synth_1/dcm_last.dcp I:/ac701_SAC/mac_ip_example.srcs/sources_1/ip/dcm_last/dcm_last.dcp
} _RESULT ] } { 
  send_msg_id runtcl-3 error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
  error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
}

if { [catch {
  write_verilog -force -mode synth_stub I:/ac701_SAC/mac_ip_example.srcs/sources_1/ip/dcm_last/dcm_last_stub.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a Verilog synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  write_vhdl -force -mode synth_stub I:/ac701_SAC/mac_ip_example.srcs/sources_1/ip/dcm_last/dcm_last_stub.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a VHDL synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  write_verilog -force -mode funcsim I:/ac701_SAC/mac_ip_example.srcs/sources_1/ip/dcm_last/dcm_last_sim_netlist.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the Verilog functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

if { [catch {
  write_vhdl -force -mode funcsim I:/ac701_SAC/mac_ip_example.srcs/sources_1/ip/dcm_last/dcm_last_sim_netlist.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the VHDL functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

if {[file isdir I:/ac701_SAC/mac_ip_example.ip_user_files/ip/dcm_last]} {
  catch { 
    file copy -force I:/ac701_SAC/mac_ip_example.srcs/sources_1/ip/dcm_last/dcm_last_stub.v I:/ac701_SAC/mac_ip_example.ip_user_files/ip/dcm_last
  }
}

if {[file isdir I:/ac701_SAC/mac_ip_example.ip_user_files/ip/dcm_last]} {
  catch { 
    file copy -force I:/ac701_SAC/mac_ip_example.srcs/sources_1/ip/dcm_last/dcm_last_stub.vhdl I:/ac701_SAC/mac_ip_example.ip_user_files/ip/dcm_last
  }
}
