# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: I:/ac701_SAC/mac_ip_example.srcs/sources_1/ip/dcm_last/dcm_last.xci
# IP: The module: 'dcm_last' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: i:/ac701_SAC/mac_ip_example.srcs/sources_1/ip/dcm_last/dcm_last_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'dcm_last'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: i:/ac701_SAC/mac_ip_example.srcs/sources_1/ip/dcm_last/dcm_last.xdc
# XDC: The top module name and the constraint reference have the same name: 'dcm_last'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: i:/ac701_SAC/mac_ip_example.srcs/sources_1/ip/dcm_last/dcm_last_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dcm_last'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# IP: I:/ac701_SAC/mac_ip_example.srcs/sources_1/ip/dcm_last/dcm_last.xci
# IP: The module: 'dcm_last' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: i:/ac701_SAC/mac_ip_example.srcs/sources_1/ip/dcm_last/dcm_last_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'dcm_last'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: i:/ac701_SAC/mac_ip_example.srcs/sources_1/ip/dcm_last/dcm_last.xdc
# XDC: The top module name and the constraint reference have the same name: 'dcm_last'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: i:/ac701_SAC/mac_ip_example.srcs/sources_1/ip/dcm_last/dcm_last_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dcm_last'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]
